### ISSUE TITLE
Roll button not working 

### ISSUE THREAD

**Issue by janberndt** [omerida/dokuwiki-randomtables#2]
The button is shown, but lacks functionality. 

Dokuwiki version: 2022-07-31a "Igor"
PHP version: 8.2.1
Plugin version: 2022-11-23 (installed via admin interface of dokuwiki)

Are there any other informations I can provide?

**Comment by omerida** [comment]
Anything in error logs? I haven't tested the plugin on PHP 8.2.1 yet.

Do the tables render?

What browser(s) have you tried?

**Comment by janberndt** [comment]
The tables render, as well as the roll button. I used the example table from the docs:
`<RANDOMTABLE card_suit>
1 Hearts
2 Spades
3 Clubs
4 Diamonds
</RANDOMTABLE>`

And this is how it is rendered:
![Screenshot_20230131_160836_Samsung Internet](https://user-images.githubusercontent.com/95169127/215798455-259503fe-8c1a-4d18-8adb-fde5b94f581a.jpg)

There are no errors in the log files, I tried the following browsers:
Chrome (Desktop) v109.0.5414.120
Microsoft Edge (Desktop) v109.0.1518.70
Chrome (mobile|android) latest version from playstore
Samsung internet (mobile)

I encountered the same problem with PHP 7.4, so I upgraded the server to have V8.2.1 instead but got the same results

**Comment by janberndt** [comment]
Okay, I have found the problem: the option compress has to be deactivated to make the roll-button work!

**Comment by janberndt** [comment]
It is a dokuwiki option under the advanced section:
![Screenshot_20230131_164938_Chrome](https://user-images.githubusercontent.com/95169127/215809179-a2554d17-8ac3-491d-a956-077fa4f6d0cc.jpg)

**Comment by omerida** [comment]
oh, that does look like a bug. I'll look into it. My JavaScript should work when minified
